[package]
name = "canrun_rs"
version = "0.1.0"
authors = ["Erik Simmler <tgecho@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im = "14.2.0"
rand = "0.7.3"
