[workspace]
members = [
    "codegen",
    "collections",
    "core",
    "basic",
    "examples",
    "readme_check",
]
default-members = [
    "codegen",
    "collections",
    "core",
    "basic",
]
