[package]
name = "canrun_codegen"
version = "0.1.0"
authors = ["Erik Simmler <tgecho@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.16"
quote = "1.0.3"
proc-macro2 = "1.0.9"
