[package]
name = "canrun"
version = "0.1.0"
authors = ["Erik Simmler <tgecho@gmail.com>"]
edition = "2018"

[dependencies]
im-rc = "14.3.0"
rand = "0.7.3"
itertools = "0.8.2"
log = "0.4.8"
canrun_codegen = {path = "../codegen"}

[dev-dependencies]
env_logger = "0.7.1"
